name: Build and Test

on:
  push:
    branches:
      - '**' # Runs when a push is made to any branch
  pull_request:
    branches:
      - '**' # Runs when a pull request is made to any branch
  workflow_dispatch:  # Runs when the workflow is manually triggered

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GCC
        run: sudo apt-get install g++ -y  # Install GCC on the runner

      - name: Build with g++
        run: g++ -o a.out main.cpp

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: a-out
          path: a.out  # Upload the a.out file as an artifact

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: a-out

      - name: Make the a.out file executable
        run: chmod +x a.out

      - name: Make the test script executable
        run: chmod +x test.sh

      - name: Run tests
        run: ./test.sh
